### ISSUE TITLE
Wiki Feedback

### ISSUE THREAD

**Issue by edherm** [Bsnernier/Momentum#12]
Hello! 

I am reviewing all group wikis today and wanted to drop this here for y’all to take a look at.

## API Routes
- [x] Do you need to include `/users/:id` in your POST and DELETE routes for likes? Could you just look up the current user's id from the session key on your req object?
- [x] You will need to change the name of one of your parameters for the post and delete requests for comments. Currently, your params will have only `{ id }` in them. You can name them something like `:commentId` an

Once these are taken care of, please drop your responses/updates here as a response to this issue.

Thanks, y'all!!
Ed

**Comment by Bsnernier** [comment]
I believe we fixed both of the issues you pointed out. For example we changed the POST route for likes to `/api/stories/:id/likes` and our POST route for comments to be `/api/stories/:id/comments/:commentid/likes`.
